-- ============================================================
-- INDIAN CITIES POPULATION ANALYTICS SYSTEM
-- SUPABASE / POSTGRESQL SETUP SCRIPT
-- Run this in Supabase -> SQL Editor (https://supabase.com/dashboard/project/tbicsxqpcgourttmnlqv/sql)
-- ============================================================

-- 1. Create the public.cities table
create table if not exists public.cities (
    id bigint generated by default as identity primary key,
    rank integer,
    city text not null,
    state text not null,
    population bigint not null check (population > 0),
    population_year integer,
    source text not null default 'Wikipedia',
    source_url text not null default 'https://en.wikipedia.org/wiki/List_of_cities_in_India_by_population',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint cities_population_year_check
        check (population_year is null or population_year between 1800 and 2200)
);

-- 2. Create Unique Index to prevent duplicate city/state/year records
create unique index if not exists cities_city_state_year_unique
    on public.cities (lower(trim(city)), lower(trim(state)), population_year);

-- 3. Performance Indexes
create index if not exists cities_population_idx on public.cities (population desc);
create index if not exists cities_rank_idx on public.cities (rank);
create index if not exists cities_state_idx on public.cities (state);
create index if not exists cities_population_year_idx on public.cities (population_year);
create index if not exists cities_city_idx on public.cities (city);

-- 4. Trigger for automatic updated_at timestamp
create or replace function public.set_cities_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists cities_set_updated_at on public.cities;
create trigger cities_set_updated_at
    before update on public.cities
    for each row
    execute function public.set_cities_updated_at();

-- 5. Row Level Security (RLS)
alter table public.cities enable row level security;

-- Public read access for dashboard/API clients using the anon key
drop policy if exists "Public can read cities" on public.cities;
create policy "Public can read cities"
    on public.cities
    for select
    to anon, authenticated
    using (true);

-- Service role full access for data ingestion and synchronization
drop policy if exists "Service role full write access" on public.cities;
create policy "Service role full write access"
    on public.cities
    for all
    to service_role
    using (true)
    with check (true);

-- 6. Grants & Permissions
grant usage on schema public to anon, authenticated, service_role;
grant select on table public.cities to anon, authenticated;
grant all on table public.cities to service_role, postgres;
grant usage, select on all sequences in schema public to service_role, postgres;

-- 7. Notify PostgREST to immediately refresh its schema cache
notify pgrst, 'reload schema';

-- ============================================================
-- 8. DISTRICTS TABLE (All 788 Districts across 36 States/UTs)
-- ============================================================
create table if not exists public.districts (
    id bigint generated by default as identity primary key,
    rank integer,
    state_rank integer,
    district text not null,
    state text not null,
    state_code text,
    headquarters text,
    population bigint not null check (population > 0),
    area_sq_km numeric,
    density_per_sq_km numeric,
    population_year integer default 2011,
    source text not null default 'Wikipedia (Census of India 2011)',
    source_url text not null default 'https://en.wikipedia.org/wiki/List_of_districts_in_India',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint districts_population_year_check
        check (population_year is null or population_year between 1800 and 2200)
);

-- Unique index to prevent duplicate district entries
create unique index if not exists districts_district_state_year_unique
    on public.districts (lower(trim(district)), lower(trim(state)), population_year);

-- Performance indexes for queries, filtering, and sorting
create index if not exists districts_population_idx on public.districts (population desc);
create index if not exists districts_rank_idx on public.districts (rank);
create index if not exists districts_state_rank_idx on public.districts (state_rank);
create index if not exists districts_state_idx on public.districts (state);
create index if not exists districts_density_idx on public.districts (density_per_sq_km desc);

-- RLS & Policies for districts
alter table public.districts enable row level security;

drop policy if exists "Public can read districts" on public.districts;
create policy "Public can read districts"
    on public.districts
    for select
    to anon, authenticated
    using (true);

drop policy if exists "Service role full write access districts" on public.districts;
create policy "Service role full write access districts"
    on public.districts
    for all
    to service_role
    using (true)
    with check (true);

grant select on table public.districts to anon, authenticated;
grant all on table public.districts to service_role, postgres;

notify pgrst, 'reload schema';

-- ============================================================
-- VERIFICATION QUERIES (Run to verify setup)
-- ============================================================
-- select count(*) as total_cities from public.cities;
-- select rank, city, state, population, population_year, source from public.cities order by population desc limit 10;
-- select state, count(*) as city_count, sum(population) as represented_population from public.cities group by state order by represented_population desc;
-- select min(population) as minimum_population, max(population) as maximum_population, avg(population) as average_population from public.cities;
