import React, { useState } from "react";
import { AlertTriangle, Database, Code, Cpu, ExternalLink, BookOpen, Layers, Copy, Check, Compass, MapPin } from "lucide-react";

export const AboutView: React.FC = () => {
  const [copied, setCopied] = useState<boolean>(false);

  const supabaseSql = `-- =====================================================================
-- COMPLETE SUPABASE POSTGRESQL SCHEMA FOR ALL-INDIA DEMOGRAPHICS
-- Tables: public.cities (339 records) and public.districts (788 records)
-- Covering: All 36 States & Union Territories of India
-- =====================================================================

-- 1. CITIES TABLE
create table if not exists public.cities (
    id bigint generated by default as identity primary key,
    rank integer,
    city text not null,
    state text not null,
    population bigint not null check (population > 0),
    population_year integer,
    source text not null default 'Census of India',
    source_url text not null default 'https://en.wikipedia.org/wiki/List_of_cities_in_India_by_population',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint cities_population_year_check
        check (population_year is null or population_year between 1800 and 2200)
);

create unique index if not exists cities_city_state_year_unique
    on public.cities (lower(trim(city)), lower(trim(state)), population_year);

create index if not exists cities_population_idx on public.cities (population desc);
create index if not exists cities_rank_idx on public.cities (rank);
create index if not exists cities_state_idx on public.cities (state);
create index if not exists cities_city_idx on public.cities (city);

-- 2. DISTRICTS TABLE (All 788 Districts across all 36 States & UTs)
create table if not exists public.districts (
    id bigint generated by default as identity primary key,
    rank integer,
    district text not null,
    state text not null,
    state_code varchar(10),
    state_rank integer,
    headquarters text,
    population bigint not null check (population > 0),
    area_sq_km numeric(12,2),
    density_per_sq_km numeric(12,2),
    source text not null default 'Census of India 2011',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists districts_district_state_unique
    on public.districts (lower(trim(district)), lower(trim(state)));

create index if not exists districts_population_idx on public.districts (population desc);
create index if not exists districts_rank_idx on public.districts (rank);
create index if not exists districts_state_idx on public.districts (state);
create index if not exists districts_density_idx on public.districts (density_per_sq_km desc);

-- 3. AUTOMATIC TIMESTAMP TRIGGERS
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists cities_set_updated_at on public.cities;
create trigger cities_set_updated_at
    before update on public.cities
    for each row
    execute function public.set_updated_at();

drop trigger if exists districts_set_updated_at on public.districts;
create trigger districts_set_updated_at
    before update on public.districts
    for each row
    execute function public.set_updated_at();

-- 4. ROW LEVEL SECURITY (RLS) POLICIES
alter table public.cities enable row level security;
alter table public.districts enable row level security;

drop policy if exists "Public can read cities" on public.cities;
create policy "Public can read cities"
    on public.cities for select to anon, authenticated using (true);

drop policy if exists "Service role full write access cities" on public.cities;
create policy "Service role full write access cities"
    on public.cities for all to service_role using (true) with check (true);

drop policy if exists "Public can read districts" on public.districts;
create policy "Public can read districts"
    on public.districts for select to anon, authenticated using (true);

drop policy if exists "Service role full write access districts" on public.districts;
create policy "Service role full write access districts"
    on public.districts for all to service_role using (true) with check (true);

-- 5. GRANTS
grant usage on schema public to anon, authenticated, service_role;
grant select on table public.cities to anon, authenticated;
grant all on table public.cities to service_role, postgres;
grant select on table public.districts to anon, authenticated;
grant all on table public.districts to service_role, postgres;
grant usage, select on all sequences in schema public to service_role, postgres;

notify pgrst, 'reload schema';`;

  const copySql = () => {
    navigator.clipboard.writeText(supabaseSql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-5 sm:space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="pb-2 border-b border-slate-200">
        <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900" id="aboutPageHeading">
          Technical Architecture & Demographic Methodology
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
          All-India Census dataset specification, district partitioning, Supabase schema, concurrency model, and API contracts
        </p>
      </div>

      {/* 1. Project Purpose */}
      <div className="bg-white p-4 sm:p-6 rounded-xl border border-slate-200 shadow-xs space-y-2 sm:space-y-3">
        <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
          <BookOpen className="w-4 h-4 sm:w-5 sm:h-5 text-blue-600" />
          1. System Purpose & Core Capabilities
        </h2>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
          The <strong>Indian Demographic Analytics System</strong> provides exhaustive population and administrative data coverage across all <strong>36 States &amp; Union Territories of India</strong>, encompassing all <strong>788 Districts</strong> and <strong>339 Major Class-I Cities</strong>. Built on high-performance in-memory indexing coupled with Supabase PostgreSQL cloud persistence, the platform delivers instant filtering, multi-tiered demographic sorting, and side-by-side comparative intelligence.
        </p>
      </div>

      {/* 2. Data Provenance & Limitations */}
      <div className="bg-white p-4 sm:p-6 rounded-xl border-l-4 border-blue-600 border-t border-r border-b border-slate-200 shadow-xs space-y-3">
        <div className="flex items-center gap-2 text-slate-900 font-bold text-sm sm:text-base">
          <AlertTriangle className="w-4 h-4 sm:w-5 sm:h-5 text-blue-600" />
          2. Official Census Provenance & Geographic Coverage
        </div>
        <div className="bg-blue-50/70 border border-blue-200 p-3 rounded-lg text-xs text-blue-950 leading-relaxed">
          <strong>Official Baseline Note:</strong> All district and city population values in this system originate from the official <strong>Census of India 2011</strong> conducted by the Office of the Registrar General &amp; Census Commissioner of India (Ministry of Home Affairs, Government of India).
        </div>
        <ul className="text-xs sm:text-sm text-slate-600 space-y-1.5 list-disc pl-5">
          <li>
            <strong>All 36 States &amp; UTs:</strong> Complete administrative coverage from Uttar Pradesh (75 districts, 199.8M population) to Lakshadweep (1 district, 64,473 population).
          </li>
          <li>
            <strong>Districts vs. Municipal Cities:</strong> Districts encompass the entire administrative territory (both urban municipal areas and rural blocks), summing to the full national census baseline of 1.21 Billion people. Cities represent statutory municipal corporation limits.
          </li>
          <li>
            <strong>Zero Synthetic Extrapolation:</strong> In strict accordance with demographic data governance standards, data points preserve the official statutory Census counts without speculative synthetic extrapolation.
          </li>
        </ul>
      </div>

      {/* 3. Layered Pipeline Architecture */}
      <div className="bg-white p-4 sm:p-6 rounded-xl border border-slate-200 shadow-xs space-y-3">
        <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
          <Layers className="w-4 h-4 sm:w-5 sm:h-5 text-indigo-600" />
          3. Multi-Tiered System Architecture
        </h2>
        <div className="bg-slate-900 text-slate-200 p-3.5 sm:p-4 rounded-xl font-mono text-[11px] sm:text-xs overflow-x-auto leading-relaxed">
{`Census of India & Wikipedia Authority
   │
   ▼ [1. Parallel Extraction & Regex Sanitization]
Data Ingestion Pipeline (ThreadPool Worker Model)
   │
   ▼ [2. Validation, Type Casting, Footnote Scrubbing]
Sanitized Datasets (788 Districts, 339 Cities, 36 States)
   │
   ├──────────────────────────────┐
   ▼                              ▼
Local CSV Exports              Supabase PostgreSQL
(data/districts.csv,           (public.districts & public.cities)
 data/cities.csv)                  │
                                   ▼
                              RESTful Analytics API Layer
                              (/api/districts, /api/states, /api/cities, /api/compare)
                                   │
                                   ▼
                              Interactive React Dashboard
                              (All-India District Explorer, Comparison Engine, Chart.js)`}
        </div>
      </div>

      {/* 4. Supabase Setup SQL */}
      <div className="bg-white p-4 sm:p-6 rounded-xl border border-slate-200 shadow-xs space-y-3">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
            <Database className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-600" />
            4. Supabase PostgreSQL Schema & Security Rules
          </h2>
          <button
            onClick={copySql}
            className="self-start sm:self-auto inline-flex items-center gap-1 text-xs font-semibold px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 rounded-lg text-slate-700 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? "Copied SQL!" : "Copy Complete SQL"}
          </button>
        </div>
        <p className="text-xs text-slate-500">
          Run this script in your Supabase SQL Editor. It creates both <code className="font-mono text-slate-800">public.cities</code> and <code className="font-mono text-slate-800">public.districts</code> with composite unique indexes, performance indexes, and Row Level Security:
        </p>
        <pre className="bg-slate-900 text-slate-200 p-3.5 rounded-xl font-mono text-[11px] overflow-x-auto max-h-64 border border-slate-800 leading-relaxed">
          {supabaseSql}
        </pre>
      </div>

      {/* 5. REST API Documentation */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="p-3.5 sm:p-4 border-b border-slate-200">
          <h3 className="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
            <Code className="w-4 h-4 text-purple-600" />
            REST API Endpoints Specification
          </h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 text-slate-600 font-semibold border-b border-slate-200">
              <tr>
                <th className="py-2.5 px-3 sm:px-4 w-16">Method</th>
                <th className="py-2.5 px-3 sm:px-4">Endpoint</th>
                <th className="py-2.5 px-3 sm:px-4">Description</th>
                <th className="py-2.5 px-3 sm:px-4">Parameters / Filters</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-mono text-slate-700">
              <tr>
                <td className="py-2 px-3"><span className="text-emerald-600 font-bold">GET</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/districts</td>
                <td className="py-2 px-3 font-sans">All 788 districts with search, state, tier filter & pagination</td>
                <td className="py-2 px-3 text-slate-500">search, state, min_population, max_population, sort, order, page, limit</td>
              </tr>
              <tr>
                <td className="py-2 px-3"><span className="text-emerald-600 font-bold">GET</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/districts/:id</td>
                <td className="py-2 px-3 font-sans">Single district record by primary key</td>
                <td className="py-2 px-3 text-slate-400">—</td>
              </tr>
              <tr>
                <td className="py-2 px-3"><span className="text-emerald-600 font-bold">GET</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/states</td>
                <td className="py-2 px-3 font-sans">All 36 States & UTs with district counts, population, and codes</td>
                <td className="py-2 px-3 text-slate-500">detailed=true</td>
              </tr>
              <tr>
                <td className="py-2 px-3"><span className="text-emerald-600 font-bold">GET</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/states/:state/districts</td>
                <td className="py-2 px-3 font-sans">All districts in a specific state/UT</td>
                <td className="py-2 px-3 text-slate-400">—</td>
              </tr>
              <tr>
                <td className="py-2 px-3"><span className="text-emerald-600 font-bold">GET</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/compare</td>
                <td className="py-2 px-3 font-sans">Comparative demographic intelligence for districts, states, or cities</td>
                <td className="py-2 px-3 text-slate-500">type (district|state|city), district1, district2, state1, state2, city1, city2</td>
              </tr>
              <tr>
                <td className="py-2 px-3"><span className="text-emerald-600 font-bold">GET</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/analytics/districts</td>
                <td className="py-2 px-3 font-sans">Summary metrics across all 788 districts</td>
                <td className="py-2 px-3 text-slate-400">—</td>
              </tr>
              <tr>
                <td className="py-2 px-3"><span className="text-emerald-600 font-bold">GET</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/cities</td>
                <td className="py-2 px-3 font-sans">339 major Class-I cities with filters & pagination</td>
                <td className="py-2 px-3 text-slate-500">search, state, sort, order, page, limit</td>
              </tr>
              <tr>
                <td className="py-2 px-3"><span className="text-purple-600 font-bold">POST</span></td>
                <td className="py-2 px-3 font-semibold text-slate-900">/api/admin/sync-districts</td>
                <td className="py-2 px-3 font-sans">Batch sync all 788 districts to Supabase</td>
                <td className="py-2 px-3 text-slate-400">—</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
